version: "3.9"
services:
  client:
    build: ./client/
    ports:
      - "3000:5173"
    volumes:
      - ./client/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    ports:
      - "5000:5000"
